name: Release Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trek_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: hello trek
      run: echo "trek ok now"
      shell: bash
  trek_second:
    runs-on: ubuntu-latest
    steps:
    - name: goodby trek
      run: echo "good by trek"
      shell: bash

 

 