name: Release Binary

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    name: Build release
    runs-on: windows-latest
    steps:
    # Your build steps here
    - name: Test
      run: echo "Testing..."
  release:
    name: Create release
    needs: build
    runs-on: windows-latest
    env:
      RELEASE_TAG: release-${{ github.sha }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    # Your release steps here
    - name: Create Release
      uses: actions/create-release@v1
      env:       
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ env.RELEASE_TAG }}
        release_name: Release ${{ env.RELEASE_TAG }}
        draft: false
        prerelease: false

 

 
